name: card_swiper
description: swiper/carousel for flutter, with multiple layouts, infinite loop. Compatible with Android & iOS.
version: 2.0.4
homepage: https://github.com/TheAnkurPanchani/flutter_swiper


environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  extended_image: ^8.1.0

dev_dependencies:
  flutter_lints_plus: ^1.0.1
  flutter_test:
    sdk: flutter

flutter:
